name: weather_forecast_bloc
description: A sample Flutter application using bloc by Seyed Abbas Ghomi.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  bloc: ^6.1.0
  flutter_bloc: ^6.0.6
  http: ^0.12.2
  sailor: ^0.7.1
  equatable: ^1.2.5
  google_maps_flutter: ^1.0.5
  flutter_staggered_grid_view: ^0.3.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  mobx_codegen: ^1.1.1+3

flutter:

  uses-material-design: true