name: weather_forecast_bloc
description: A sample Flutter application by Seyed Abbas Ghomi.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  http: ^0.13.3
  equatable: ^2.0.2
  beamer: ^0.13.3
  google_maps_flutter: ^2.0.6
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  pedantic: ^1.11.0

flutter:

  uses-material-design: true


